version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    groups:
      dev-dependencies:
        patterns:
          - '@eslint/*'
          - '@typescript-eslint/*'
          - 'eslint'
          - 'typescript-eslint'
          - 'vitest'
          - 'typescript'
