/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all projects
         * @description Returns all projects from all sources, optionally filtered by source
         */
        get: {
            parameters: {
                query?: {
                    /** @description Filter by source (e.g., 'claude', 'kimi') */
                    source?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ProjectsResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectID}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List sessions for a project
         * @description Returns all sessions belonging to a specific project
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Project ID (URL-encoded path) */
                    projectID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.SessionsResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get session content
         * @description Returns session metadata and entries with optional pagination
         */
        get: {
            parameters: {
                query?: {
                    /** @description Maximum number of entries to return (0 for all) */
                    limit?: number;
                    /** @description Number of entries to skip */
                    offset?: number;
                };
                header?: never;
                path: {
                    /** @description Session file path (URL-encoded) */
                    path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.SessionResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available trace sources
         * @description Returns all configured trace sources (e.g., Claude Code, Kimi Code)
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.SourcesResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "server.APISourceInfo": {
            available?: boolean;
            base_path?: string;
            name?: string;
        };
        "server.ErrorResponse": {
            error?: string;
            message?: string;
        };
        "server.ProjectsResponse": {
            projects?: components["schemas"]["thinkt.Project"][];
        };
        "server.SessionResponse": {
            entries?: components["schemas"]["thinkt.Entry"][];
            has_more?: boolean;
            meta?: components["schemas"]["thinkt.SessionMeta"];
            total?: number;
        };
        "server.SessionsResponse": {
            sessions?: components["schemas"]["thinkt.SessionMeta"][];
        };
        "server.SourcesResponse": {
            sources?: components["schemas"]["server.APISourceInfo"][];
        };
        "thinkt.ContentBlock": {
            is_error?: boolean;
            media_data?: string;
            /** @description Image/document block */
            media_type?: string;
            /** @description For signed/encrypted thinking */
            signature?: string;
            /** @description Text block */
            text?: string;
            /** @description Thinking block */
            thinking?: string;
            tool_input?: unknown;
            tool_name?: string;
            /** @description Tool result block */
            tool_result?: string;
            /** @description Tool use block */
            tool_use_id?: string;
            type?: string;
        };
        "thinkt.Entry": {
            /** @description Content (one of these will be set) */
            content_blocks?: components["schemas"]["thinkt.ContentBlock"][];
            cwd?: string;
            git_branch?: string;
            is_checkpoint?: boolean;
            /** @description For branched conversations */
            is_sidechain?: boolean;
            /** @description Source-specific extras */
            metadata?: {
                [key: string]: unknown;
            };
            /** @description Metadata */
            model?: string;
            /** @description For branching conversations */
            parent_uuid?: string;
            role?: components["schemas"]["thinkt.Role"];
            /** @description Provenance - where this entry came from */
            source?: components["schemas"]["thinkt.Source"];
            /** @description Simple text shortcut */
            text?: string;
            timestamp?: string;
            usage?: components["schemas"]["thinkt.TokenUsage"];
            /** @description Core identification */
            uuid?: string;
            /** @description Which machine/host */
            workspace_id?: string;
        };
        "thinkt.Project": {
            /** @description Human-readable path */
            display_path?: string;
            id?: string;
            last_modified?: string;
            /** @description Display name */
            name?: string;
            /** @description Full filesystem path */
            path?: string;
            session_count?: number;
            /** @description Which tool */
            source?: components["schemas"]["thinkt.Source"];
            /** @description Which machine/host */
            workspace_id?: string;
        };
        /** @enum {string} */
        "thinkt.Role": "user" | "assistant" | "tool" | "system" | "summary" | "progress" | "checkpoint";
        "thinkt.SessionMeta": {
            /** @description Number of files: 0=unknown, 1=single, 2+=chunked */
            chunk_count?: number;
            created_at?: string;
            entry_count?: number;
            /** @description Size in bytes */
            file_size?: number;
            first_prompt?: string;
            /** @description Path to session file */
            full_path?: string;
            git_branch?: string;
            id?: string;
            model?: string;
            modified_at?: string;
            /** @description Normalized project path */
            project_path?: string;
            /** @description Which tool (kimi, claude) */
            source?: components["schemas"]["thinkt.Source"];
            summary?: string;
            /** @description Which machine/host */
            workspace_id?: string;
        };
        /** @enum {string} */
        "thinkt.Source": "kimi" | "claude";
        "thinkt.TokenUsage": {
            cache_creation_input_tokens?: number;
            cache_read_input_tokens?: number;
            input_tokens?: number;
            output_tokens?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
