/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/indexer/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get indexer health status
         * @description Returns whether the indexer binary is available and the database path
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/indexer/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get indexer server status
         * @description Returns the current state of the indexer server including sync/embedding progress, model info, and uptime. Requires a running indexer server.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.IndexerStatusResponse"];
                    };
                };
                /** @description Unauthorized - invalid or missing token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/open-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open a path in an application
         * @description Opens the specified path in an allowed application (e.g., Finder, VS Code)
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Open-in request */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["server.OpenInRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.OpenInResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Unauthorized - invalid or missing token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/open-in/apps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List allowed apps for open-in
         * @description Returns the list of enabled applications that can be used with open-in
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.AllowedAppsResponse"];
                    };
                };
                /** @description Unauthorized - invalid or missing token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all projects
         * @description Returns all projects from all sources, optionally filtered by source
         */
        get: {
            parameters: {
                query?: {
                    /** @description Filter by source (e.g., 'claude', 'kimi') */
                    source?: string;
                    /** @description Include projects with path_exists=false (default false) */
                    include_deleted?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ProjectsResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Unauthorized - invalid or missing token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectID}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List sessions for a project
         * @description Returns all sessions belonging to a specific project
         */
        get: {
            parameters: {
                query?: {
                    /** @description Source name (recommended to avoid ambiguous project IDs) */
                    source?: string;
                };
                header?: never;
                path: {
                    /** @description Project ID (URL-encoded path) */
                    projectID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.SessionsResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Unauthorized - invalid or missing token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{source}/{projectID}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List sessions for a project in a source
         * @description Returns all sessions belonging to a specific project within a specific source
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Source name (e.g., 'claude', 'kimi') */
                    source: string;
                    /** @description Project ID (URL-encoded path) */
                    projectID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.SessionsResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Unauthorized - invalid or missing token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search across indexed sessions
         * @description Search for text within the original session files using the DuckDB index
         */
        get: {
            parameters: {
                query: {
                    /** @description Search query text */
                    q: string;
                    /** @description Filter by project name (substring match) */
                    project?: string;
                    /** @description Filter by source (claude, kimi) */
                    source?: string;
                    /** @description Maximum total matches (default 50) */
                    limit?: number;
                    /** @description Maximum matches per session (default 2, 0 for no limit) */
                    limit_per_session?: number;
                    /** @description Enable case-sensitive matching (default false) */
                    case_sensitive?: boolean;
                    /** @description Treat query as a regular expression (default false) */
                    regex?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.SearchResponse"];
                    };
                };
                /** @description Bad Request - missing query */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Unauthorized - invalid or missing token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Service Unavailable - indexer not found */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/semantic-search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Semantic search across indexed sessions
         * @description Search for sessions by meaning using on-device embeddings. Returns sessions ranked by semantic similarity. Requires the indexer with a synced embedding index.
         */
        get: {
            parameters: {
                query: {
                    /** @description Natural language search query */
                    q: string;
                    /** @description Filter by project name (substring match) */
                    project?: string;
                    /** @description Filter by source (claude, kimi, gemini, copilot, codex, qwen) */
                    source?: string;
                    /** @description Maximum number of results (default 20) */
                    limit?: number;
                    /** @description Cosine distance threshold (0-2, lower is more similar) */
                    max_distance?: number;
                    /** @description Apply diversity scoring to return results from different sessions */
                    diversity?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.SemanticSearchResponse"];
                    };
                };
                /** @description Bad Request - missing query */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Unauthorized - invalid or missing token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Service Unavailable - indexer not found */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get session content
         * @description Returns session metadata and entries with optional pagination
         */
        get: {
            parameters: {
                query?: {
                    /** @description Maximum number of entries to return (0 for all) */
                    limit?: number;
                    /** @description Number of entries to skip */
                    offset?: number;
                };
                header?: never;
                path: {
                    /** @description Session file path (URL-encoded) */
                    path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.SessionResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Unauthorized - invalid or missing token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{path}/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get session metadata
         * @description Returns session metadata, role counts, and entry previews. Set summary_only=true for quick user-message previews.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Maximum summaries/previews to return (default 50; default 5 when summary_only=true) */
                    limit?: number;
                    /** @description Number of summaries/previews to skip */
                    offset?: number;
                    /** @description Roles to exclude (repeat query param or comma-separated). Defaults to checkpoint. */
                    exclude_roles?: string[];
                    /** @description Return lightweight user-message previews only */
                    summary_only?: boolean;
                    /** @description Summary ordering: index (default) or length */
                    sort_by?: string;
                };
                header?: never;
                path: {
                    /** @description Session file path (URL-encoded) */
                    path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.SessionMetadataResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Unauthorized - invalid or missing token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{path}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get or execute resume command for a session
         * @description Returns the command, arguments, and working directory needed to resume a session.
         *     With ?action=exec, spawns the command in the configured terminal instead.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Set to 'exec' to spawn the command in a terminal */
                    action?: string;
                };
                header?: never;
                path: {
                    /** @description Session file path (URL-encoded) */
                    path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ResumeResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Unauthorized - invalid or missing token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Source does not support resume */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available trace sources
         * @description Returns all configured trace sources (e.g., Claude Code, Kimi Code)
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.SourcesResponse"];
                    };
                };
                /** @description Unauthorized - invalid or missing token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get index usage statistics
         * @description Returns aggregate usage statistics including total tokens and most used tools
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.StatsResponse"];
                    };
                };
                /** @description Unauthorized - invalid or missing token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Service Unavailable - indexer not found */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all teams
         * @description Returns all Claude Code teams discovered on this machine
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.TeamsResponse"];
                    };
                };
                /** @description Unauthorized - invalid or missing token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{teamName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get team details
         * @description Returns team details including resolved member-to-session mappings
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Team name */
                    teamName: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["thinkt.Team"];
                    };
                };
                /** @description Unauthorized - invalid or missing token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{teamName}/members/{memberName}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List team member messages
         * @description Returns inbox messages for a specific team member
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Team name */
                    teamName: string;
                    /** @description Member name */
                    memberName: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.TeamMessagesResponse"];
                    };
                };
                /** @description Unauthorized - invalid or missing token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{teamName}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List team tasks
         * @description Returns the shared task board for a team
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Team name */
                    teamName: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.TeamTasksResponse"];
                    };
                };
                /** @description Unauthorized - invalid or missing token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/themes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available themes
         * @description Returns all available themes (built-in and user themes) with their color definitions
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ThemesResponse"];
                    };
                };
                /** @description Unauthorized - invalid or missing token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["server.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "config.AppInfo": {
            enabled?: boolean;
            id?: string;
            name?: string;
        };
        "server.AllowedAppsResponse": {
            apps?: components["schemas"]["config.AppInfo"][];
        };
        "server.ErrorResponse": {
            error?: string;
            message?: string;
        };
        "server.IndexerStatusProgressInfo": {
            chunks_done?: number;
            chunks_total?: number;
            done?: number;
            entries?: number;
            message?: string;
            project?: number;
            project_name?: string;
            project_total?: number;
            session_id?: string;
            total?: number;
        };
        "server.IndexerStatusResponse": {
            embed_progress?: components["schemas"]["server.IndexerStatusProgressInfo"];
            model?: string;
            model_dim?: number;
            running?: boolean;
            state?: string;
            sync_progress?: components["schemas"]["server.IndexerStatusProgressInfo"];
            uptime_seconds?: number;
            watching?: boolean;
        };
        "server.OpenInRequest": {
            /** @description App ID (e.g., "finder", "vscode", "cursor") */
            app?: string;
            /** @description Path to open */
            path?: string;
        };
        "server.OpenInResponse": {
            message?: string;
            success?: boolean;
        };
        "server.ProjectsResponse": {
            projects?: components["schemas"]["thinkt.Project"][];
        };
        "server.ResumeResponse": {
            args?: string[];
            command?: string;
            dir?: string;
        };
        "server.SearchMatch": {
            line_num?: number;
            preview?: string;
            role?: string;
        };
        "server.SearchResponse": {
            sessions?: components["schemas"]["server.SearchSessionResult"][];
            total_matches?: number;
        };
        "server.SearchSessionResult": {
            matches?: components["schemas"]["server.SearchMatch"][];
            path?: string;
            project_name?: string;
            session_id?: string;
            source?: string;
        };
        "server.SemanticSearchResponse": {
            results?: components["schemas"]["server.SemanticSearchResult"][];
        };
        "server.SemanticSearchResult": {
            chunk_index?: number;
            distance?: number;
            entry_uuid?: string;
            first_prompt?: string;
            line_number?: number;
            project_name?: string;
            role?: string;
            session_id?: string;
            session_path?: string;
            source?: string;
            timestamp?: string;
            tool_name?: string;
            total_chunks?: number;
            word_count?: number;
        };
        "server.SessionMetadataResponse": {
            description?: string;
            entry_summary?: components["schemas"]["server.entrySummary"][];
            error?: components["schemas"]["server.toolErrorDetail"];
            meta?: components["schemas"]["server.sessionMetaInfo"];
            returned_summaries?: number;
            role_counts?: {
                [key: string]: number;
            };
            total_content_bytes?: number;
            total_entries?: number;
        };
        "server.SessionResponse": {
            entries?: components["schemas"]["thinkt.Entry"][];
            has_more?: boolean;
            meta?: components["schemas"]["thinkt.SessionMeta"];
            total?: number;
        };
        "server.SessionsResponse": {
            sessions?: components["schemas"]["thinkt.SessionMeta"][];
        };
        "server.SourceInfo": {
            available?: boolean;
            base_path?: string;
            can_resume?: boolean;
            name?: string;
        };
        "server.SourcesResponse": {
            sources?: components["schemas"]["server.SourceInfo"][];
        };
        "server.StatsResponse": {
            tool_usage?: {
                [key: string]: number;
            };
            total_entries?: number;
            total_projects?: number;
            total_sessions?: number;
            total_tokens?: number;
        };
        "server.TeamMessagesResponse": {
            messages?: components["schemas"]["thinkt.TeamMessage"][];
        };
        "server.TeamTasksResponse": {
            tasks?: components["schemas"]["thinkt.TeamTask"][];
        };
        "server.TeamsResponse": {
            teams?: components["schemas"]["thinkt.Team"][];
        };
        "server.ThemeColors": {
            /** @description UI chrome */
            accent?: string;
            assistant_block?: components["schemas"]["server.ThemeStyle"];
            assistant_label?: components["schemas"]["server.ThemeStyle"];
            border_active?: string;
            border_inactive?: string;
            /** @description Confirm dialog */
            confirm_prompt?: components["schemas"]["server.ThemeStyle"];
            confirm_selected?: components["schemas"]["server.ThemeStyle"];
            confirm_unselected?: components["schemas"]["server.ThemeStyle"];
            text_muted?: components["schemas"]["server.ThemeStyle"];
            /** @description Text styles */
            text_primary?: components["schemas"]["server.ThemeStyle"];
            text_secondary?: components["schemas"]["server.ThemeStyle"];
            thinking_block?: components["schemas"]["server.ThemeStyle"];
            thinking_label?: components["schemas"]["server.ThemeStyle"];
            tool_call_block?: components["schemas"]["server.ThemeStyle"];
            tool_label?: components["schemas"]["server.ThemeStyle"];
            tool_result_block?: components["schemas"]["server.ThemeStyle"];
            /** @description Conversation blocks */
            user_block?: components["schemas"]["server.ThemeStyle"];
            /** @description Labels */
            user_label?: components["schemas"]["server.ThemeStyle"];
        };
        "server.ThemeInfo": {
            active?: boolean;
            colors?: components["schemas"]["server.ThemeColors"];
            description?: string;
            embedded?: boolean;
            name?: string;
        };
        "server.ThemeStyle": {
            bg?: string;
            bold?: boolean;
            fg?: string;
            italic?: boolean;
            underline?: boolean;
        };
        "server.ThemesResponse": {
            active?: string;
            themes?: components["schemas"]["server.ThemeInfo"][];
        };
        "server.entrySummary": {
            content_length?: number;
            has_thinking?: boolean;
            has_tool_result?: boolean;
            has_tool_use?: boolean;
            index?: number;
            preview?: string;
            role?: string;
            timestamp?: string;
        };
        "server.sessionMetaInfo": {
            created_at?: string;
            git_branch?: string;
            id?: string;
            model?: string;
            modified_at?: string;
            path?: string;
            source?: string;
        };
        "server.toolErrorDetail": {
            code?: string;
            details?: string;
            message?: string;
        };
        "thinkt.ContentBlock": {
            is_error?: boolean;
            media_data?: string;
            /** @description Image/document block */
            media_type?: string;
            /** @description For signed/encrypted thinking */
            signature?: string;
            /** @description Text block */
            text?: string;
            /** @description Thinking block */
            thinking?: string;
            tool_input?: unknown;
            tool_name?: string;
            /** @description Tool result block */
            tool_result?: string;
            /** @description Tool use block */
            tool_use_id?: string;
            type?: string;
        };
        "thinkt.Entry": {
            /** @description Resolved agent name (e.g., "researcher") */
            agent_id?: string;
            /** @description Content (one of these will be set) */
            content_blocks?: components["schemas"]["thinkt.ContentBlock"][];
            cwd?: string;
            git_branch?: string;
            is_checkpoint?: boolean;
            /** @description For branched conversations */
            is_sidechain?: boolean;
            /** @description Source-specific extras */
            metadata?: {
                [key: string]: unknown;
            };
            /** @description Metadata */
            model?: string;
            /** @description For branching conversations */
            parent_uuid?: string;
            role?: components["schemas"]["thinkt.Role"];
            /** @description Provenance - where this entry came from */
            source?: components["schemas"]["thinkt.Source"];
            /** @description Raw source identifier (e.g., "ab17e07") */
            source_agent_id?: string;
            /** @description Simple text shortcut */
            text?: string;
            timestamp?: string;
            usage?: components["schemas"]["thinkt.TokenUsage"];
            /** @description Core identification */
            uuid?: string;
            /** @description Which machine/host */
            workspace_id?: string;
        };
        "thinkt.Project": {
            /** @description Human-readable path */
            display_path?: string;
            id?: string;
            last_modified?: string;
            /** @description Display name */
            name?: string;
            /** @description Full filesystem path */
            path?: string;
            /** @description Whether the project directory still exists on disk */
            path_exists?: boolean;
            session_count?: number;
            /** @description Which tool */
            source?: components["schemas"]["thinkt.Source"];
            /** @description Root storage path for this source */
            source_base_path?: string;
            /** @description Which machine/host */
            workspace_id?: string;
        };
        /** @enum {string} */
        "thinkt.Role": "user" | "assistant" | "tool" | "system" | "summary" | "progress" | "checkpoint";
        "thinkt.SessionMeta": {
            /** @description Number of files: 0=unknown, 1=single, 2+=chunked */
            chunk_count?: number;
            created_at?: string;
            entry_count?: number;
            /** @description Size in bytes */
            file_size?: number;
            first_prompt?: string;
            /** @description Path to session file */
            full_path?: string;
            git_branch?: string;
            id?: string;
            model?: string;
            modified_at?: string;
            /** @description Normalized project path */
            project_path?: string;
            /** @description Which tool (kimi, claude) */
            source?: components["schemas"]["thinkt.Source"];
            summary?: string;
            /** @description Which machine/host */
            workspace_id?: string;
        };
        /** @enum {string} */
        "thinkt.Source": "thinkt" | "claude" | "codex" | "copilot" | "gemini" | "kimi" | "qwen";
        "thinkt.Team": {
            created_at?: string;
            description?: string;
            /** @description LeadAgentID is the config-format agent ID (e.g., "team-lead@myteam"). */
            lead_agent_id?: string;
            /**
             * @description LeadSessionID is the UUID of the team lead's session.
             *     Subagent sessions live under projects/{projectDir}/{LeadSessionID}/subagents/
             */
            lead_session_id?: string;
            members?: components["schemas"]["thinkt.TeamMember"][];
            /** @description Name is the team identifier (directory name under ~/.claude/teams/). */
            name?: string;
            /** @description Source provenance */
            source?: components["schemas"]["thinkt.Source"];
            status?: components["schemas"]["thinkt.TeamStatus"];
            workspace_id?: string;
        };
        "thinkt.TeamMember": {
            /** @description AgentID is the config-format ID (e.g., "researcher@myteam"). */
            agent_id?: string;
            /** @description AgentType classifies the member (e.g., "team-lead", "general-purpose"). */
            agent_type?: string;
            color?: string;
            cwd?: string;
            joined_at?: string;
            model?: string;
            /** @description Name is the short display name (e.g., "researcher"). */
            name?: string;
            /**
             * @description SessionPath is the path to this member's subagent JSONL file.
             *     Populated during discovery. Empty for unresolved members.
             */
            session_path?: string;
            /**
             * @description SourceAgentID is the short hash used in session JSONL entries
             *     (e.g., "ab17e07"). Populated when correlating team config with
             *     session data. May be empty if not yet resolved.
             */
            source_agent_id?: string;
        };
        "thinkt.TeamMessage": {
            color?: string;
            from?: string;
            read?: boolean;
            text?: string;
            timestamp?: string;
        };
        /** @enum {string} */
        "thinkt.TeamStatus": "active" | "inactive";
        "thinkt.TeamTask": {
            active_form?: string;
            blocked_by?: string[];
            blocks?: string[];
            description?: string;
            id?: string;
            is_internal?: boolean;
            owner?: string;
            /** @description "pending", "in_progress", "completed", "deleted" */
            status?: string;
            subject?: string;
        };
        "thinkt.TokenUsage": {
            cache_creation_input_tokens?: number;
            cache_read_input_tokens?: number;
            input_tokens?: number;
            output_tokens?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
